# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerDeploy < Formula
  desc "Deploy a docker-compose project to a remote VPS via SSH — no git required on the remote"
  homepage "https://github.com/webcane/docker-deploy"
  version "0.7.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.7.6/docker-deploy_darwin_amd64.tar.gz"
      sha256 "51329eafef801abf825aab50ff6884c36d733f23bbf105fabfcf9e30926cba12"

      define_method(:install) do
        bin.install "docker-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.7.6/docker-deploy_darwin_arm64.tar.gz"
      sha256 "97be156ae4beb42d2d009dcb0331e19412491a59152cda136f8f07ef7401f9ee"

      define_method(:install) do
        bin.install "docker-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.7.6/docker-deploy_linux_amd64.tar.gz"
      sha256 "11c48eca8d1b3ab36d08dab633a8c97f2a10b4223ca22841aff4be1d71b86385"
      define_method(:install) do
        bin.install "docker-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.7.6/docker-deploy_linux_arm64.tar.gz"
      sha256 "f0b82c0570e0d6e7549885e2fa01920f5dc27d51d04b4386e444d3b51c15d72f"
      define_method(:install) do
        bin.install "docker-deploy"
      end
    end
  end

  def post_install
    cli_plugins = Pathname.new("#{Dir.home}/.docker/cli-plugins")
    cli_plugins.mkpath
    target = "#{cli_plugins}/docker-deploy"
    src = "#{opt_bin}/docker-deploy"
    File.delete(target) if File.symlink?(target)
    begin
      File.symlink(src, target)
    rescue Errno::EPERM
      opoo "Could not create symlink automatically. Run manually:\n" \
           "  ln -sf #{opt_bin}/docker-deploy ~/.docker/cli-plugins/docker-deploy"
    end
  end

  def sandbox_allowlist?
    true
  end

  def uninstall
    target = "#{Dir.home}/.docker/cli-plugins/docker-deploy"
    File.delete(target) if File.exist?(target)
  end

  test do
    system "#{bin}/docker-deploy", "docker-cli-plugin-metadata"
  end
end
