# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerDeploy < Formula
  desc "Deploy a docker-compose project to a remote VPS via SSH — no git required on the remote"
  homepage "https://github.com/webcane/docker-deploy"
  version "0.13.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.13.1/docker-deploy_darwin_amd64.tar.gz"
      sha256 "f3a0f47ff1ef1f33ead50beaf12d58536021e70936176cffe27dd92f11458e35"

      define_method(:install) do
        bin.install "docker-deploy"
        (lib/"docker/cli-plugins").install_symlink bin/"docker-deploy"
        (share/"zsh/site-functions").install "_docker-deploy"
        (share/"bash-completion/completions").install "docker-deploy.bash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.13.1/docker-deploy_darwin_arm64.tar.gz"
      sha256 "4a247615ebcdaf867bbb837e07ebfef634d92b9d7cb8f895bed55a652972a6fd"

      define_method(:install) do
        bin.install "docker-deploy"
        (lib/"docker/cli-plugins").install_symlink bin/"docker-deploy"
        (share/"zsh/site-functions").install "_docker-deploy"
        (share/"bash-completion/completions").install "docker-deploy.bash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.13.1/docker-deploy_linux_amd64.tar.gz"
      sha256 "2d095e9f40cd16c8948587b47358dc52c701528dcafb0bebdce01445603e68a3"
      define_method(:install) do
        bin.install "docker-deploy"
        (lib/"docker/cli-plugins").install_symlink bin/"docker-deploy"
        (share/"zsh/site-functions").install "_docker-deploy"
        (share/"bash-completion/completions").install "docker-deploy.bash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.13.1/docker-deploy_linux_arm64.tar.gz"
      sha256 "2ffb9d0bc3b89b6d396e7d73c3ab238f3d5707efff69cc89e03e046b3d21df51"
      define_method(:install) do
        bin.install "docker-deploy"
        (lib/"docker/cli-plugins").install_symlink bin/"docker-deploy"
        (share/"zsh/site-functions").install "_docker-deploy"
        (share/"bash-completion/completions").install "docker-deploy.bash"
      end
    end
  end

  def caveats
    return if Hardware::CPU.intel?

    <<~EOS
      Apple Silicon: Docker does not search #{HOMEBREW_PREFIX}/lib/docker/cli-plugins by default.
      Make the plugin visible via one of:

      Option 1 — symlink into your CLI plugins directory:
        mkdir -p ~/.docker/cli-plugins
        ln -sf #{opt_bin}/docker-deploy ~/.docker/cli-plugins/docker-deploy

      Option 2 — add Homebrew's plugin directory to ~/.docker/config.json:
        "cliPluginsExtraDirs": ["#{HOMEBREW_PREFIX}/lib/docker/cli-plugins"]
    EOS
  end

  test do
    system "#{bin}/docker-deploy", "docker-cli-plugin-metadata"
  end
end
