# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DockerDeploy < Formula
  desc "Deploy a docker-compose project to a remote VPS via SSH — no git required on the remote"
  homepage "https://github.com/webcane/docker-deploy"
  version "0.9.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.9.3/docker-deploy_darwin_amd64.tar.gz"
      sha256 "27beed5de5163702f9ad0cf4c62fafdd2bf8f4eaff0067ac00bb172b578cba79"

      define_method(:install) do
        bin.install "docker-deploy"
        (lib/"docker/cli-plugins").install_symlink bin/"docker-deploy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.9.3/docker-deploy_darwin_arm64.tar.gz"
      sha256 "b181af1120f19026eecada7fd72c214eaa35f1a762208a8b35544873c8bea95b"

      define_method(:install) do
        bin.install "docker-deploy"
        (lib/"docker/cli-plugins").install_symlink bin/"docker-deploy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.9.3/docker-deploy_linux_amd64.tar.gz"
      sha256 "c65c70d20686cae712b5ec9f036fbdc3d2c2a9a612fefdddd913f0ca82c5dfea"
      define_method(:install) do
        bin.install "docker-deploy"
        (lib/"docker/cli-plugins").install_symlink bin/"docker-deploy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/webcane/docker-deploy/releases/download/v0.9.3/docker-deploy_linux_arm64.tar.gz"
      sha256 "ca473716da13e18922b658e85b3fedd8023b76e35d1e5f0c27dcec87a5a472bf"
      define_method(:install) do
        bin.install "docker-deploy"
        (lib/"docker/cli-plugins").install_symlink bin/"docker-deploy"
      end
    end
  end

  def caveats
    <<~EOS
      docker-deploy is a Docker plugin. For Docker to find the plugin, add "cliPluginsExtraDirs" to ~/.docker/config.json:
        "cliPluginsExtraDirs": [
            "#{HOMEBREW_PREFIX}/lib/docker/cli-plugins"
        ]
    EOS
  end

  test do
    system "#{bin}/docker-deploy", "docker-cli-plugin-metadata"
  end
end
